POST http://localhost:3000/register
Content-Type: application/json

{
    "name":"Syam",
    "email":"Syam@fs.com",
    "password": "Lucky12345"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"lucky@fs.com",
    "password": "Lucky12345"
}