POST http://localhost:3000/register
Content-Type: application/json

{
    "name":"Sundar",
    "email":"Sundar@fs.com",
    "password":"Lucky12345"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"Syam@fs.com",
    "password": "Lucky12345"
}

###
GET http://localhost:3000/all-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw

###
GET http://localhost:3000/user/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw

###
PUT  http://localhost:3000/user/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw
Content-Type: application/json

{
    "name":"Syam",
    "email":"Syam@fs.com",
    "password": "Lucky12345"
}

###
DELETE http://localhost:3000/user/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw

###
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw

###
// Check Category with Clothing or Electronics
GET http://localhost:3000/products/Clothing
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw

###
POST http://localhost:3000/add-product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw
Content-Type: application/json

{
    "name":"Blue Cap",
    "category":"Clothing",
    "description":"A Nice Blue Cap",
    "price":599
}

###
GET http://localhost:3000/product/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw

###
PUT  http://localhost:3000/product/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw
Content-Type: application/json

{
    "name":"I Phone 14",
    "category":"Electronics",
    "description":"The iPhone is a smartphone made by Apple that combines a computer, iPod, digital camera and cellular phone into one device with a touchscreen interface",
    "price":49999
}

###
DELETE http://localhost:3000/product/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlN5YW1AZnMuY29tIiwiaWF0IjoxNjk3Nzk0ODM3fQ.L1JuDhuE9MuBbRM4sdKIz0hAZiizAtO1aaDFS5QNXsw